version: '3.8'

services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
    depends_on:
      - db
     
  db:
    image: postgres:12
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: Eventtoday_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
